### ISSUE TITLE
Can we use drupal_twiggy for a full theme?

### ISSUE THREAD

**Issue by n3storm** [aklump/drupal_twiggy#1]
Can we use drupal_twiggy for a full theme?

Thanks!

**Comment by aklump** [comment]
Hi @n3storm, I'm not exactly sure what you're asking.  But I've used it for several custom themes, when I'm providing my own theme hooks.  I have never used it for theme overrides, such as page.tpl.php, etc.  If you're asking about licensing, I've just added the license file, which I can see was missing.

**Comment by n3storm** [comment]
Sorry my bad wording.

We want to create a full twig theme for drupal 7.

Stork is a copy of Stark drupal theme:

`stork/template.php `

```
function stork_theme_registry_alter(&$themes) {
   twiggy_use_twig('html', $themes);
}
```

` stork/templates/html.html.twig` content is: 

```
Hello world
{{doctype}}
```

Browser output says: **string(34) "Variable "doctype" does not exist."** 

Any ideas on how to start with this? populating twig templates with drupal variables?
Is this beyond your goals?

**Comment by n3storm** [comment]
We are now using "twiggy_use_twig" with page with better results. Also we have enabled debug function and we can see now what is going on.

**Comment by aklump** [comment]
@n3storm It sounds like you have what you need?  Honestly I haven't worked with this module for maybe a year so it's not all fresh in my mind.  If you run into issues, I can offer paid support, but it would have to be in January.  You can contact me for work through my website: http://intheloftstudios.com/

**Comment by n3storm** [comment]
Thank you so much @aklump
